[general]
logconfig="/etc/burrow/logging.cfg"

[zookeeper]
servers=["zookeeper:2181"]
timeout=6
lock-path="/burrow/notifier"
root-path="/local"

[cluster.local]
class-name="kafka"
servers=["192.168.208.2:9092"]
offsets-topic="__consumer_offsets"

[consumer.local]
class-name="kafka"
servers=["192.168.208.2:9092"]
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"
cluster="local"

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver.default]
address=":8000"
